lunchman/lunchman/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import debug_toolbar


urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'website.views.logout_view', name='logout_view'),

    url(r'^$', 'website.views.home', name='home'),

    url(r'^settings/$', 'website.views.user_settings', name='user_settings'),

    url(r'^attendance/(?P<action>\S+)/$', 'website.views.update_attendance', name='update_attendance'),
    url(r'^attendance/$', 'website.views.update_attendance', name='update_attendance_def'),

    url(r'^attendance_ajax/$', 'website.views.update_attendance_ajax', name='update_attendance_ajax'),

    url(r'^new_meal_ticket/$', 'website.views.new_meal_ticket', name='new_meal_ticket'),
]

lunchman/website/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

from website.utils import fix_meal_name


TIME_CHOICES = (
    ('ordinary', 'Subo a las 13h'),
    ('delayed', 'Subo más tarde, esperad'),
    ('non-attending', 'No subo'),
)

BEHAVIOUR_CHOICES = (
    ('daily', 'Lo especifico cada día'),
    ('default_no', 'Por defecto NO subo a diario'),
)


###     MealTicket
####################################################################################################

class MealTicket(models.Model):

    owner = models.ForeignKey(User)

    remaining_meals = models.PositiveSmallIntegerField(
        default=20,
    )

    purchased = models.DateField(
        auto_now_add=True,
    )

    class Meta:
        unique_together = ('owner', 'purchased')

    def __unicode__(self):
        return '%s %s - %s (%d)' % (self.owner.first_name, self.owner.last_name, self.purchased, self.remaining_meals)


###     AttendedMeal
###################################################################################################

class AttendedMeal(models.Model):

    person = models.ForeignKey(User)

    date = models.DateField()

    preferred_time = models.CharField(
        max_length=15,
        default='ordinary',
        choices=TIME_CHOICES,
    )

    class Meta:
        unique_together = ('person', 'date')


###     Menu
###################################################################################################

class Menu(models.Model):

    date = models.DateField(
        unique=True,
    )

    def __unicode__(self):
        return u'%s' % (self.date)

    class Meta:
        ordering = ['-date']


###     FirstCourse
###################################################################################################

class FirstCourse(models.Model):

    menu = models.ForeignKey('Menu')

    meal = models.CharField(
        max_length=75,
    )

    def save(self, *args, **kwargs):

        self.meal = fix_meal_name(self.meal)

        super(FirstCourse, self).save(*args, **kwargs)


###     SecondCourse
###################################################################################################

class SecondCourse(models.Model):

    menu = models.ForeignKey('Menu')

    meal = models.CharField(
        max_length=75,
    )

    def save(self, *args, **kwargs):

        self.meal = fix_meal_name(self.meal)

        super(SecondCourse, self).save(*args, **kwargs)


###     Dessert
###################################################################################################

class Dessert(models.Model):

    menu = models.ForeignKey('Menu')

    meal = models.CharField(
        max_length=75,
    )

    def save(self, *args, **kwargs):

        self.meal = fix_meal_name(self.meal)

        super(Dessert, self).save(*args, **kwargs)


###     UserSettings
###################################################################################################

class UserSettings(models.Model):

    user = models.ForeignKey(User)

    default_behaviour = models.CharField(
        max_length=15,
        default='daily',
        choices=BEHAVIOUR_CHOICES,
    )

lunchman/website/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from website.models import BEHAVIOUR_CHOICES


###     LoginForm
####################################################################################################

class LoginForm(AuthenticationForm):

    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'username',
        })
    )

    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'password',
        })
    )


###     UserSettingsForm
####################################################################################################

class UserSettingsForm(forms.Form):

    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
        }),
        required=False,
    )

    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
        }),
        required=False,
    )

    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
        }),
        required=False,
    )

    email = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
        }),
        required=False,
    )

    remaining_meals = forms.IntegerField(
        max_value=20,
        min_value=0,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
        }),
        required=False,
    )

    default_behaviour = forms.ChoiceField(
        # max_length=15,
        widget=forms.RadioSelect(attrs={
            'class': 'radio',
            'type': 'radio',
            'name': 'behaviour-radio',
        }),
        choices=BEHAVIOUR_CHOICES,
    )

lunchman/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Lunchman</title>

        <link rel="icon" href="{% static 'img/favicon.png' %}" />

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <i class="fa fa-cutlery"></i>
                        &nbsp;
                        lunchman
                    </a>
                </div>

                <div class="navbar-right">
                    {% if user.is_authenticated %}
                        <div id="logged-user" class="user-div">
                            {{ user.first_name }} {{ user.last_name }}
                            <sup>
                                <span class="badge" title="{{ remaining_meals }} comidas restantes">
                                    {{ remaining_meals }}
                                </span>
                            </sup>
                        </div>

                        <div id="dropdown-div" class="dropdown clearfix">
                            <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>
                                    <a href="{% url 'user_settings' %}">
                                        <i class="fa fa-cog">
                                            &nbsp;
                                            Configuración
                                        </i>
                                    </a>
                                </li>

                                <li role="separator" class="divider"></li>

                                <li>
                                    <a href="{% url 'logout_view' %}">
                                        <i class="fa fa-sign-out">
                                            &nbsp;
                                            Salir
                                        </i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <form class="form-inline navbar-form" method="post" action="{% url 'home' %}">
                        {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="id_username">Username</label>
                                {{ form.username }}
                            </div>

                            <div class="form-group">
                                <label class="sr-only" for="id_password">Password</label>
                                {{ form.password }}
                            </div>

                            <button type="submit" class="btn btn-primary" value="login">Entrar</button>
                            <input type="hidden" name="next" value="" />
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="modal fade" id="ticket-modal" tabindex="-1" role="dialog" aria-labelledby="modal-new-ticket">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="modal-new-ticket">Compra de ticket</h4>
                    </div>

                    <div class="modal-body">
                        Si has comprado un nuevo ticket del Colegio Mayor (20 servicios) haz click en <em>"Añadir Ticket"</em>, lo que añadirá un nuevo bono de 20 servicios a tu cuenta.
                        <br>
                        De lo contrario, cierra esta ventana.
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
                        <a href="{% url 'new_meal_ticket' %}" class="btn btn-sm btn-primary">
                            Añadir ticket
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            {% block main_content %}{% endblock %}
        </div>

        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}
    </body>
</html>

lunchman/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}


{% block main_content %}

    <div class="row">

        <div class="col-md-6">
            <br>
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                {% include 'menu.html' with weekday='lunes' menu=monday_menu %}
                {% include 'menu.html' with weekday='martes' menu=tuesday_menu %}
                {% include 'menu.html' with weekday='miércoles' menu=wednesday_menu %}
                {% include 'menu.html' with weekday='jueves' menu=thursday_menu %}
                {% include 'menu.html' with weekday='viernes' menu=friday_menu %}
            </div>
        </div>

        <div class="col-md-4  col-md-offset-1">
            {% if user.is_authenticated %}
                <p class="summary centered">
                    <span class="ordinary">{{ ordinary_attendance|length }}</span>
                    <span class="delayed">{{ delayed_attendance|length }}</span>
                    <span class="non-attendance">{{ non_attendance|length }}</span>
                    <span class="non-confirmed">{{ non_confirmed_attendance|length }}</span>

                </p>

                <table id="attendance-table" class="table table-condensed table-striped">
                    {% for ordinary_attendee in ordinary_attendance %}
                        <tr class="success">
                            <td>
                                {{ ordinary_attendee.person.first_name }} {{ ordinary_attendee.person.last_name }}

                                {% if ordinary_attendee.person == user and before_lunchtime %}
                                    <div class="pull-right">
                                        <button class="btn btn-warning btn-xs" onclick="updateAttendance('delayed');">
                                            <i class="fa fa-clock-o"></i>
                                        </button>

                                        &nbsp;

                                        <button class="btn btn-danger btn-xs" onclick="updateAttendance('non-attending');">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                    {% for delayed_attendee in delayed_attendance %}
                        <tr class="warning">
                            <td>
                                {{ delayed_attendee.person.first_name }} {{ delayed_attendee.person.last_name }}

                                {% if delayed_attendee.person == user and before_lunchtime %}
                                    <div class="pull-right">
                                        <button class="btn btn-success btn-xs" onclick="updateAttendance('ordinary');">
                                            <i class="fa fa-thumbs-up"></i>
                                        </button>

                                        &nbsp;

                                        <button class="btn btn-danger btn-xs" onclick="updateAttendance('non-attending');">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                    {% for non_attendee in non_attendance %}
                        <tr class="danger">
                            <td>
                                {{ non_attendee.person.first_name }} {{ non_attendee.person.last_name }}

                                {% if non_attendee.person == user and before_lunchtime %}
                                    <div class="pull-right">
                                        <button class="btn btn-success btn-xs" onclick="updateAttendance('ordinary');">
                                            <i class="fa fa-thumbs-up"></i>
                                        </button>

                                        &nbsp;

                                        <button class="btn btn-warning btn-xs" onclick="updateAttendance('delayed');">
                                            <i class="fa fa-clock-o"></i>
                                        </button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                    {% for non_confirmed_attendee in non_confirmed_attendance %}
                        <tr class="active">
                            <td>
                                {{ non_confirmed_attendee.first_name }} {{ non_confirmed_attendee.last_name }}

                                {% if non_confirmed_attendee == user and before_lunchtime %}
                                    <div class="pull-right">
                                        <button class="btn btn-success btn-xs" onclick="updateAttendance('ordinary');">
                                            <i class="fa fa-thumbs-up"></i>
                                        </button>

                                        &nbsp;

                                        <button class="btn btn-warning btn-xs" onclick="updateAttendance('delayed');">
                                            <i class="fa fa-clock-o"></i>
                                        </button>

                                        &nbsp;

                                        <button class="btn btn-danger btn-xs" onclick="updateAttendance('non-attending');">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>

                <br>
                <i id="green-circle" class="fa fa-circle"></i>&emsp;Sube a comer
                <br>
                <i id="yellow-circle" class="fa fa-circle"></i>&emsp;Subirá más tarde
                <br>
                <i id="red-circle" class="fa fa-circle"></i>&emsp;No sube a comer
                <br>
                <i id="grey-circle" class="fa fa-circle"></i>&emsp;No ha confirmado
            {% endif %}
        </div>

    </div>

{% endblock %}



{% block scripts %}

    <script src="{% static 'js/handlebars.runtime-v4.0.2.js' %}"></script>
    <script src="{% static 'js/templates/templates.js' %}"></script>
    <script src="{% static 'js/jquery.ajax.min.js' %}"></script>

    <script>
        function updateAttendance(action) {
            ajaxGet("{% url 'update_attendance_ajax' %}", function(content){

                if (content['remaining_meals'] == 1 && action != 'non-attending') {

                    var last_meal_modal_template = Handlebars.templates['last_meal_modal'];
                    $('body').append(last_meal_modal_template(content));

                    $('#last-meal-modal').modal('show');

                    $("#ok-and-ticket").click(function() {
                        ajaxGet("{% url 'new_meal_ticket' %}", function() {
                            window.location.replace("{% url 'update_attendance_def' %}" + action);
                        });
                    });

                    $("#ok").click(function() {
                        window.location.replace("{% url 'update_attendance_def' %}" + action);
                    });
                }
                else if (content['remaining_meals'] == 0 && action != 'non-attending') {

                    var no_meals_modal_template = Handlebars.templates['no_meals_modal'];
                    $('body').append(no_meals_modal_template(content));

                    $('#no-meals-modal').modal('show');

                    $("#ok-and-ticket").click(function() {
                        ajaxGet("{% url 'new_meal_ticket' %}", function() {
                            window.location.replace("{% url 'update_attendance_def' %}" + action);
                        });
                    });
                }
                else {
                    window.location.replace("{% url 'update_attendance_def' %}" + action);
                };
            });
        };
    </script>

{% endblock %}

lunchman/templates/menu.html
<div class="panel {% if menu.date == today %}panel-primary{% else %}panel-default{% endif %}">
    <div class="panel-heading" role="tab" id="heading-{{ weekday }}">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ weekday }}" aria-expanded="true" aria-controls="{{ weekday }}">
                {{ weekday|title }}
            </a>
            <small class="pull-right">
                {{ menu.date|date:"d M" }}
            </small>
        </h4>
    </div>

    <div id="{{ weekday }}" class="panel-collapse collapse {% if menu.date == today %}in{% endif %}" role="tabpanel" aria-labelledby="heading-{{ weekday }}">
        <div class="panel-body">
            <dl>
                <dt>Primeros platos</dt>
                <dd>
                    <ul>
                        {% for first_course in menu.firstcourse_set.all %}
                            <li>
                                {{ first_course.meal }}
                                &nbsp;
                                <a href="http://www.google.com/images?q={{ first_course.meal }}" title="¿Qué podría ser esto?">
                                    <i class="fa fa-question-circle"></i>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </dd>

                <dt>Segundos platos</dt>
                <dd>
                    <ul>
                        {% for second_course in menu.secondcourse_set.all %}
                            <li>
                                {{ second_course.meal }}
                                &nbsp;
                                <a href="http://www.google.com/images?q={{ second_course.meal }}" title="¿Qué podría ser esto?">
                                    <i class="fa fa-question-circle"></i>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </dd>

                <dt>Postres</dt>
                <dd>
                    <ul>
                        {% for dessert in menu.dessert_set.all %}
                            <li>
                                {{ dessert.meal }}
                                &nbsp;
                                <a href="http://www.google.com/images?q={{ dessert.meal }}" title="¿Qué podría ser esto?">
                                    <i class="fa fa-question-circle"></i>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </dd>
            </dl>
        </div>
    </div>
</div>

lunchman/templates/user_settings.html
{% extends "base.html" %}
{% load staticfiles %}


{% block main_content %}

    <div class="alert alert-info centered" role="alert">
        En esta sección puedes actualizar tus datos y preferencias por defecto. Si deseas realizar cualquier otra acción, contacta con <strong>Aritz Bilbao</strong>&nbsp;<i class="fa fa-heart"></i>
.
    </div>

    <br>

    <form class="form-horizontal" method="post" action="{% url 'user_settings' %}">
    {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-1">
                <div class="form-group">
                    <label class="control-label col-md-4" for="id_username">
                        Usuario
                    </label>
                    <div class="col-md-8">
                        {{ form.username }}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4" for="id_first_name">
                        Nombre
                    </label>
                    <div class="col-md-8">
                        {{ form.first_name }}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4" for="id_last_name">
                        Apellido
                    </label>
                    <div class="col-md-8">
                        {{ form.last_name }}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4" for="id_email">
                        Email
                    </label>
                    <div class="col-md-8">
                        {{ form.email }}
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-md-offset-1">
                <span id="def_behaviour_title">Comportamiento predeterminado</span>
                <div class="radio">
                    {{ form.default_behaviour }}
                </div>

                <br>

                <div class="form-group">
                    <label class="control-label col-md-8" for="id_remaining_meals">
                        Comidas restantes
                    </label>
                    <div class="col-md-4">
                        {{ form.remaining_meals }}
                    </div>
                </div>

                <br>

                <div class="centered">
                    <button type="submit" class="btn btn-primary btn-sm" value="submit">Guardar</button>
                    <a href="{% url 'home' %}" class="btn btn-danger btn-sm">Volver</a>
                    <input type="hidden" name="next" value="" />
                </div>
            </div>
        </div>
    </form>

{% endblock %}



{% block scripts %}

    <script>
        $('#id_username').attr("placeholder", "{{ user.username }}");
        $('#id_first_name').attr("placeholder", "{{ user.first_name }}");
        $('#id_last_name').attr("placeholder", "{{ user.last_name }}");
        $('#id_email').attr("placeholder", "{{ user.email }}");

        {% if default_behaviour == 'daily' %}
            $("#id_default_behaviour_0").prop("checked", true);
        {% elif default_behaviour == 'default_no' %}
            $("#id_default_behaviour_1").prop("checked", true);
        {% endif %}
    </script>

{% endblock %}